apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstpythonapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstpythonapi
  template:
    metadata:
      labels:
        app: firstpythonapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: firstpythonapi
        image: dangtestacr.azurecr.io/sample/firstpythonapi
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
          name: python
      imagePullSecrets:
        - name: dangacr-secret
